services:
  frontend:
    build:
      context: src/frontend/.
      network: host
      args:
        UID: ${UID:-1000}
    ports:
      - "127.0.0.1:8501:8501"
    volumes:
      - ./src/frontend:/app
    depends_on:
      backend:
        condition: service_healthy
        restart: true
  backend:
    build:
      context: src/backend/.
      network: host
      args:
        UID: ${UID:-1000}
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./src/backend:/app