name: CD

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Get code
        run: cd /opt/codebase && git pull && git checkout dev

      - name: Start services
        run: cd /opt/codebase && docker compose --profile full up -d